services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/public:/usr/share/nginx/html
    depends_on:
      - web
      - api
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    expose:
      - "8080"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: unless-stopped
