name: modis-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.3
  - xarray>=2023.5
  - netcdf4>=1.6
  - h5netcdf>=1.2
  - hdf4>=4.2
  - pyhdf
  - gdal
  - scikit-learn>=1.2
  - lightgbm>=4.0
  - pytorch
  - joblib>=1.3
  - pyyaml>=6.0
  - pytest
  - pytest-cov
