# Configuration for training the MODIS cloud seedability ensemble.
data:
  features_path: data/processed/example_features.csv
  label_column: cloud_seeding_label
  split_column: split
  # Optional: list of columns to use as model inputs. Comment to auto-infer numeric features.
  # feature_columns:
  #   - cloud_optical_thickness_mean
  #   - cloud_effective_radius_mean
  splits:
    train: [train]
    val: [val]
    test: [test]
  granule_column: granule

lightgbm:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: -1
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_samples: 20
  early_stopping_rounds: 50

resmlp:
  hidden_dim: 512
  num_blocks: 4
  dropout: 0.1
  expansion: 4

resmlp_training:
  epochs: 150
  batch_size: 512
  learning_rate: 0.001
  weight_decay: 0.01
  early_stopping_patience: 25

training:
  artifacts_dir: ml_artifacts
  seed: 2024
  num_classes: 3
